version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      # Install SonarQube Scanner
      - npm install -g sonarqube-scanner

  build:
    commands:
      # Install Node.js dependencies
      - npm install
      # Build the React app
      - npm run build

  post_build:
    commands:
      # SonarCloud analysis
      - sonarqube-scanner \
          -Dsonar.projectKey=reactmml \
          -Dsonar.organization=arjit547 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${SONAR_LOGIN}

      # Continue with AWS CodeBuild steps (e.g., deploying artifacts)
      - aws s3 sync build/ s3://${BUCKET_NAME}

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
