version: 0.2

phases:
  pre_build:
    commands:
      # Print environment information for debugging
      - env
      - echo "Current directory: $(pwd)"
      - echo "Files in /usr/local/bin/: $(ls /usr/local/bin/)"
      - /usr/local/bin/git-secrets --version

      # Download and install Git-Secrets
      - curl -sSL -o /usr/local/bin/git-secrets https://github.com/awslabs/git-secrets/releases/latest/download/git-secrets
      - chmod +x /usr/local/bin/git-secrets
      - /usr/local/bin/git-secrets --install --force

      # Run Git-Secrets scan
      - /usr/local/bin/git-secrets --scan -r HEAD --debug

  build:
    commands:
      # Your actual build steps go here
      - npm install
      - npm run build

  post_build:
    commands:
      # Sync the build artifacts to the main S3 bucket
      - aws s3 sync build/ s3://${BUCKET_NAME}

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
