version: 0.2

phases:
  pre_build:
    commands:
      # Install Git-Secrets using apt-get
      - apt-get update
      - apt-get install -y git-secrets

      # Run Git-Secrets scan
      - git-secrets --install --no-rotate --no-protection --quiet

      # Run Git-Secrets scan
      - git-secrets --scan -r HEAD

  build:
    commands:
      # Your actual build steps go here
      - npm install
      - npm run build

  post_build:
    commands:
      # Sync the build artifacts to the main S3 bucket
      - aws s3 sync build/ s3://${BUCKET_NAME}

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
