version: 0.2

phases:
  pre_build:
    commands:
      # Install Git-Secrets manually
      - curl -sSL -o git-secrets https://github.com/awslabs/git-secrets/releases/download/3.1.0/git-secrets
      - chmod +x git-secrets
      - sudo mv git-secrets /usr/local/bin/

      # Run Git-Secrets scan
      - git-secrets --install --quiet

      # Run Git-Secrets scan
      - git-secrets --scan -r HEAD

  build:
    commands:
      # Your actual build steps go here
      - npm install
      - npm run build

  post_build:
    commands:
      # Sync the build artifacts to the main S3 bucket
      - aws s3 sync build/ s3://${BUCKET_NAME}

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
