version: 0.2

phases:
  pre_build:
    commands:
      # Download and install git-secrets
      - wget -O /tmp/git-secrets https://github.com/awslabs/git-secrets/releases/download/3.3.0/git-secrets
      - chmod +x /tmp/git-secrets
      - mv /tmp/git-secrets /usr/local/bin/git-secrets

      # Run Git-Secrets commands
      - git secrets --register-aws
      - git secrets --install -f
      - git secrets --scan -r HEAD

  build:
    commands:
      # Your actual build steps go here
      - npm install
      - npm run build

  post_build:
    commands:
      # Sync the build artifacts to the main S3 bucket
      - aws s3 sync build/ s3://${BUCKET_NAME}

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
