version: 0.2

phases:
  pre_build:
    commands:
      # Install Git
      - apt-get install git -y

      # Download and install Git-Secrets using curl
      - curl -sSL -o /tmp/git-secrets https://github.com/awslabs/git-secrets/releases/download/3.3.0/git-secret
      - chmod +x /tmp/git-secrets
      - sudo mv /tmp/git-secrets /usr/local/bin/
      - ls -l /usr/local/bin/git-secrets

      # Change to the source code directory
      - cd $CODEBUILD_SRC_DIR

      # Initialize Git repository (if not already initialized)
      - git init

      # Configure Git user identity (replace with your details)
      - git config user.name "Arjit"
      - git config user.email "ks5015232@gmail.com"

      # Run Git-Secrets installation
      - /usr/local/bin/git-secrets --install

      # Run Git-Secrets scan
      - /usr/local/bin/git-secrets --scan

  build:
    commands:
      # Your build commands go here
      - npm install
      - npm run build

  post_build:
    commands:
      # Sync the build artifacts to the main S3 bucket
      - aws s3 sync build/ s3://${BUCKET_NAME}

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
