version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://arjitbt
      - aws cloudfront create-invalidation --distribution-id EN0Y2N19HQBJN --paths "/*"
artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes











  version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 rm s3://arjitbt --recursive   # Delete existing contents of the S3 bucket
      - aws s3 sync build/ s3://arjitbt      # Sync new build artifacts to the S3 bucket
      - aws cloudfront create-invalidation --distribution-id EN0Y2N19HQBJN --paths "/*"

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes







