version: 0.2

phases:
  pre_build:
    commands:
      # Install Git and Git-Secrets
      - apt-get update
      - apt-get install git git-secrets -y

      # Change to the source code directory
      - cd $CODEBUILD_SRC_DIR

      # Initialize Git repository (if not already initialized)
      - git init

      # Configure Git user identity (replace with your details)
      - git config user.name "Arjit"
      - git config user.email "ks5015232@gmail.com"

      # Disable tput and say commands in git-secrets
      - sed -i 's|tput -T "${GIT_SECRETS_TPUT_TYPE}" setaf 3 1>/dev/null 2>&1|: #tput -T "${GIT_SECRETS_TPUT_TYPE}" setaf 3 1>/dev/null 2>&1|' /usr/bin/git-secrets
      - sed -i 's/say "Do not commit AWS secret keys."/say "Do not commit AWS secret keys."/g' /usr/bin/git-secrets

      # Run Git-Secrets installation
      - git secrets --install

      # Run Git-Secrets scan
      - git secrets --scan

  build:
    commands:
      # Your build commands go here
      - npm install
      - npm run build

  post_build:
    commands:
      # Sync the build artifacts to the main S3 bucket
      - aws s3 sync build/ s3://${BUCKET_NAME}

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
