version: 0.2

phases:
  pre_build:
    commands:
      #- echo "Setting up environment variables"
      #- export MY_SECRET_KEY=$MY_HOME_TEST

      - echo "Installing Git"
      - apt-get update
      - apt-get install git -y
      - pwd
      - ls -al

      - echo "Installing Git secrets"
      - wget --quiet https://github.com/awslabs/git-secrets/archive/1.3.0.tar.gz
      - tar -xzf 1.3.0.tar.gz
      - cd git-secrets-1.3.0 && sudo make install && cd ..
      - git-secrets --register-aws
      - git-secrets --scan -r .
      - if git-secrets --scan -r . | grep -q 'ERROR'; then exit 1; fi

  build:
    commands:
      - echo "Installing npm dependencies"
      - npm install

      - echo "Building the project"
      - npm run build

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
