version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Modify based on your Node.js version requirement
  pre_build:
    commands:
      # Install Git and Git-Secrets
      - apt-get update
      - apt-get install git git-secrets -y

      # Initialize Git repository
      - git init

      # Run Git-Secrets installation
      - sed -i 's/say "Do not commit AWS secret keys."/echo "Do not commit AWS secret keys."/g' /usr/bin/git-secrets
      - git secrets --install -f

      # Scan for secrets
      - git secrets --scan

  build:
    commands:
      # Your build commands go here
      - npm install
      - npm run build

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
