version: 0.2

phases:
  pre_build:
    commands:
      - echo "Setting up environment variables"
      - export MY_SECRET_KEY=$MY_HOME_TEST

      - echo "Installing Git"
      - apt-get update
      - apt-get install git -y

      - echo "Installing Git secrets"
      - wget --quiet https://github.com/awslabs/git-secrets/archive/1.3.0.tar.gz
      - tar -xzf 1.3.0.tar.gz
      - cd git-secrets-1.3.0 && sudo make install && cd ..
      - git-secrets --register-aws
      - aws s3 cp <(git-secrets --scan -r .) s3://${BUCKET_NAME}/git-secrets-output.txt
      - if grep -q 'ERROR' <(git-secrets --scan -r .); then exit 1; fi

  build:
    commands:
      - echo "Installing npm dependencies"
      - npm install

      - echo "Building the project"
      - npm run build

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
