version: 0.2

phases:
  pre_build:
    commands:
      # Download Git-Secrets using wget
      - wget -O /usr/local/bin/git-secrets https://github.com/awslabs/git-secrets/releases/download/3.1.0/git-secrets
      - chmod +x /usr/local/bin/git-secrets

      # Run Git-Secrets installation
      - /usr/local/bin/git-secrets --install

      # Run Git-Secrets scan
      - /usr/local/bin/git-secrets --scan

  build:
    commands:
      # Your actual build steps go here
      - npm install
      - npm run build

  post_build:
    commands:
      # Sync the build artifacts to the main S3 bucket
      - aws s3 sync build/ s3://${BUCKET_NAME}

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
