version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y curl unzip
      - curl -sSL -o /tmp/git-secrets.zip https://github.com/awslabs/git-secrets/archive/3.1.0.zip
      - unzip /tmp/git-secrets.zip -d /tmp
      - chmod +x /tmp/git-secrets-3.1.0/git-secrets
      - sudo mv /tmp/git-secrets-3.1.0/git-secrets /usr/local/bin/git-secrets
      - git secrets --register-aws
      - git secrets --install -f
      - git secrets --scan -r HEAD

  build:
    commands:
      # Your actual build steps go here
      - npm install
      - npm run build

  post_build:
    commands:
      # Sync the build artifacts to the main S3 bucket
      - aws s3 sync build/ s3://${BUCKET_NAME}

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
