version: 0.2

phases:
  pre_build:
    commands:
      # Install curl
      - apt-get update
      - apt-get install -y curl

      # Download and install git-secrets
      - curl -sSL -o /tmp/git-secrets.zip https://github.com/awslabs/git-secrets/archive/3.1.0.zip
      - unzip /tmp/git-secrets.zip -d /tmp
      - cd /tmp/git-secrets-3.1.0 && make install

      # Run Git-Secrets commands
      - git secrets --register-aws
      - git secrets --install -f
      - git secrets --scan -r HEAD

  build:
    commands:
      # Your actual build steps go here
      - npm install
      - npm run build

  post_build:
    commands:
      # Sync the build artifacts to the main S3 bucket
      - aws s3 sync build/ s3://${BUCKET_NAME}

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
