version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y curl tar
      - curl -sSL -o /tmp/git-secrets.tar.gz https://github.com/awslabs/git-secrets/archive/3.1.0.tar.gz
      - tar -xzf /tmp/git-secrets.tar.gz -C /tmp
      - cd /tmp/git-secrets-3.1.0
      - sudo make install
      - git secrets --register-aws
      - git secrets --install -f
      - git secrets --scan -r HEAD

  build:
    commands:
      # Your actual build steps go here
      - npm install
      - npm run build

  post_build:
    commands:
      # Sync the build artifacts to the main S3 bucket
      - aws s3 sync build/ s3://${BUCKET_NAME}

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
